/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActiveUserClientDataModel { 
    companyId?: number;
    companyName?: string | null;
    startDate?: string;
    endDate?: string;
}

