/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelClientDataModel } from './modelClientDataModel';
import { VatTypeDataModel } from './vatTypeDataModel';


export interface CompanyDataModel { 
    id?: number;
    uuid?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    deletedAt?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    deletedBy?: string | null;
    businessName?: string | null;
    vatNumber?: string | null;
    fiscalCode?: string | null;
    sdi?: string | null;
    referent?: string | null;
    email?: string | null;
    phone?: string | null;
    vatType?: VatTypeDataModel;
    client?: ModelClientDataModel;
}

