/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateOrUpdateOrderDataModel { 
    internalRef?: string | null;
    externalRef?: string | null;
    workerId?: number;
    teamTailorUserRef?: number | null;
    startDate: string;
    endDate: string;
    hourRate?: number;
    resourceCosts?: number;
    hours?: number | null;
    companyId?: number;
    invoiceRowInfo?: string | null;
}

