/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sex } from './sex';


export interface CreateUserDataModel { 
    firstName: string;
    lastName: string;
    userIdentifier: string;
    teamTailorUserRef?: number | null;
    username: string;
    email: string | null;
    password: string | null;
    confirmPassword: string | null;
    birthDate: string;
    sex: Sex;
    roles: Array<number> | null;
    talent?: string | null;
}
export namespace CreateUserDataModel {
}


