/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CvChangeAddRequest } from './cvChangeAddRequest';
import { CvExtractedData } from './cvExtractedData';


export interface CvChangesAddRequest { 
    changes?: Array<CvChangeAddRequest> | null;
    current?: CvExtractedData;
}

