/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CvBasicInfo } from './cvBasicInfo';
import { CvOtherSkill } from './cvOtherSkill';
import { TrainingAndCertificateItem } from './trainingAndCertificateItem';
import { CvCustomSection } from './cvCustomSection';
import { LanguageItem } from './languageItem';
import { CvExperience } from './cvExperience';
import { CvHighlight } from './cvHighlight';


export interface CvExtractedData { 
    basicInfo?: CvBasicInfo;
    highlights?: Array<CvHighlight> | null;
    otherSkills?: Array<CvOtherSkill> | null;
    experiences?: Array<CvExperience> | null;
    trainingAndCertificates?: Array<TrainingAndCertificateItem> | null;
    customSections?: Array<CvCustomSection> | null;
    languages?: Array<LanguageItem> | null;
    language?: string | null;
    aiAnalysisSummary?: string | null;
}

