/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CvModelData } from './cvModelData';


export interface CvModelDataIPaginatedResponse { 
    items?: Array<CvModelData> | null;
    totalCount?: number;
    pageSize?: number;
    pageIndex?: number;
    readonly totalPages?: number;
    readonly hasPrevious?: boolean;
    readonly hasNext?: boolean;
}

