/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CvOtherSkill { 
    id?: string | null;
    years?: number | null;
    name?: string | null;
    confirmed?: boolean;
    confirmedByAi?: boolean;
    confirmedBy?: string | null;
    additionalNotes?: string | null;
}

