/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';
import { SubjectType } from './subjectType';


export interface DocumentBuilderConfig { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    rowTemplate?: string | null;
    rowNameTemplate?: string | null;
    group?: boolean;
    company?: Company;
    companyId?: number;
    dueDays?: number;
    subjectType?: SubjectType;
}
export namespace DocumentBuilderConfig {
}


