/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmailTemplateModel { 
    id?: number;
    uuid?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    deletedAt?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    deletedBy?: string | null;
    key?: string | null;
    subject?: string | null;
    body?: string | null;
    isSystem?: boolean;
    father?: EmailTemplateModel;
    fatherId?: number | null;
    templateDataTest?: { [key: string]: any; } | null;
}

