/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeCostDataModel { 
    id?: number;
    userId?: number;
    year?: number;
    month?: number;
    name?: string | null;
    surname?: string | null;
    fiscalCode?: string | null;
    workingSite?: string | null;
    dateStart?: string | null;
    dateEnd?: string | null;
    contractType?: string | null;
    role?: string | null;
    salary?: number;
    net?: number;
    variableGross?: number;
    monthlyGross?: number;
    companyContribute?: number;
    inail?: number;
    directCosts?: number;
    tfr?: number;
    bonus13?: number;
    bonus14?: number;
    other?: number;
    contribution?: number;
    indirectMaturedCosts?: number;
    indirectProvidedCosts?: number;
    grossCosts?: number;
}

