/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeeCostGroupDataModel } from './employeeCostGroupDataModel';


export interface EmployeeCostGroupDataModelPaginatedResponse { 
    items?: Array<EmployeeCostGroupDataModel> | null;
    totalCount?: number;
    pageSize?: number;
    pageIndex?: number;
}

