/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComparisonOperator } from './comparisonOperator';
import { FilterDtoType } from './filterDtoType';
import { LogicalOperator } from './logicalOperator';


export interface FilterNodeDto { 
    type: FilterDtoType;
    property?: string | null;
    operator?: ComparisonOperator;
    value?: any | null;
    compareToProps?: Array<string> | null;
    logic?: LogicalOperator;
    children?: Array<FilterNodeDto> | null;
}
export namespace FilterNodeDto {
}


