/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecretResponse } from './secretResponse';
import { FolderDto } from './folderDto';


export interface FolderDetailDto { 
    folderId?: number;
    name?: string | null;
    description?: string | null;
    ownerUserId?: number;
    parentFolderId?: number | null;
    subFolders?: Array<FolderDto> | null;
    secrets?: Array<SecretResponse> | null;
}

