/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FolderDto { 
    folderId?: number;
    name?: string | null;
    description?: string | null;
    ownerUserId?: number;
    parentFolderId?: number | null;
    secretCount?: number;
    subFolderCount?: number;
    isOwner?: boolean;
}

