/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupMemberDto } from './groupMemberDto';


export interface GroupDto { 
    groupId?: number;
    name?: string | null;
    isOwner?: boolean;
    members?: Array<GroupMemberDto> | null;
}

