/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupMemberDto { 
    userId?: number;
    userEmail?: string | null;
    userDisplayName?: string | null;
}

