/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Email } from './email';
import { CompanyDataModel } from './companyDataModel';
import { TimeSheetDataModel } from './timeSheetDataModel';


export interface InvoicesDataModel { 
    id?: number;
    company?: CompanyDataModel;
    month?: number;
    year?: number;
    timesheets?: Array<TimeSheetDataModel> | null;
    confirmedTimesheets?: number;
    readonly confirmed?: string | null;
    generated?: number;
    all?: number;
    readonly status?: string | null;
    mailSender?: string | null;
    grouped?: boolean;
    emails?: Array<Email> | null;
}

