/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RelationType } from './relationType';
import { UiResourceRefMetadata } from './uiResourceRefMetadata';


export interface LookupMetadata { 
    relationType?: RelationType;
    entity?: UiResourceRefMetadata;
    displayFields?: Array<string> | null;
    displayFieldsSeparator?: string | null;
    createForm?: string | null;
    updateForm?: string | null;
    enableDelete?: boolean;
    freeInput?: boolean;
    filterByKey?: string | null;
}
export namespace LookupMetadata {
}


