/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortingDto } from './sortingDto';
import { FilterNodeDto } from './filterNodeDto';


export interface PaginatedRequestDto { 
    filters?: FilterNodeDto;
    sorting?: Array<SortingDto> | null;
}

