/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecoveryMethodType } from './recoveryMethodType';


export interface RecoveryEnvelopeDto { 
    methodType?: RecoveryMethodType;
    saltBase64?: string | null;
    iterations?: number | null;
    ciphertextBase64?: string | null;
    nonceBase64?: string | null;
    tagBase64?: string | null;
    metadata?: string | null;
}
export namespace RecoveryEnvelopeDto {
}


