/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const RelationType = {
    OneToOne: 'OneToOne',
    OneToMany: 'OneToMany',
    ManyToOne: 'ManyToOne',
    ManyToMany: 'ManyToMany'
} as const;
export type RelationType = typeof RelationType[keyof typeof RelationType];

