/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VaultSecret } from './vaultSecret';
import { SecretPermission } from './secretPermission';
import { VaultGroup } from './vaultGroup';
import { UserDevice } from './userDevice';


export interface SecretDeviceEnvelope { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    secretId?: number;
    secret?: VaultSecret;
    deviceId?: number;
    device?: UserDevice;
    wrappedSecretKeyBase64?: string | null;
    permission?: SecretPermission;
    sharedByUserId?: number;
    groupId?: number | null;
    group?: VaultGroup;
}
export namespace SecretDeviceEnvelope {
}


