/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Sex = {
    Male: 'MALE',
    Female: 'FEMALE'
} as const;
export type Sex = typeof Sex[keyof typeof Sex];

