/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SubjectType = {
    InternalOda: 'InternalOda',
    ExternalOda: 'ExternalOda',
    Project: 'Project',
    Consultant: 'Consultant',
    None: 'None'
} as const;
export type SubjectType = typeof SubjectType[keyof typeof SubjectType];

