/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Talent } from './talent';


export interface TalentTalentHubResponse { 
    data?: Array<Talent> | null;
    meta?: object;
}

