/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimesheetMediaDto { 
    id: number;
    name: string;
    key: string;
    uuid: string;
    url: string;
    isProforma: boolean;
    timesheetId: number;
    clientId: number;
    clientName: string;
    month: number;
    year: number;
}

