/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrainingType } from './trainingType';


export interface TrainingAndCertificateItem { 
    id?: string | null;
    type?: TrainingType;
    title?: string | null;
    issuer?: string | null;
    year?: string | null;
    description?: string | null;
    confirmed?: boolean;
    confirmedBy?: string | null;
    additionalNotes?: string | null;
}
export namespace TrainingAndCertificateItem {
}


