/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UiFormFieldMetadata } from './uiFormFieldMetadata';
import { FormKind } from './formKind';


export interface UiFormMetadata { 
    api?: string | null;
    kind: FormKind;
    formName: string | null;
    fields?: { [key: string]: UiFormFieldMetadata; } | null;
    column?: number;
}
export namespace UiFormMetadata {
}


