/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UiTableColumnMetadata { 
    name: string | null;
    className?: string | null;
    templateName?: string | null;
    headerTemplateName?: string | null;
    label?: string | null;
    order?: number;
    hidden?: boolean | null;
    sortable?: boolean | null;
    filterable?: boolean | null;
    deepFilterable?: boolean | null;
    width?: number | null;
    freeze?: boolean | null;
    additionalData?: { [key: string]: any; } | null;
    options?: Array<object> | null;
    tooltip?: string | null;
    description?: string | null;
    defaultValue?: any | null;
    format?: string | null;
}

