/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateCostsResultDataModel { 
    imported?: number;
    skipped?: number;
    skippedFiscalCodes?: Array<string> | null;
}

