/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserMediaDto } from './userMediaDto';


export interface UserMediaDtoMediaRequestPaginatedData { 
    items?: Array<UserMediaDto> | null;
    totalCount?: number;
    pageSize?: number;
    pageIndex?: number;
}

