/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDataModel } from './userDataModel';


export interface UserDataModelIPaginatedResponse { 
    items?: Array<UserDataModel> | null;
    totalCount?: number;
    pageSize?: number;
    pageIndex?: number;
    readonly totalPages?: number;
    readonly hasPrevious?: boolean;
    readonly hasNext?: boolean;
}

