/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cv } from './cv';
import { Organization } from './organization';
import { Address } from './address';
import { Sex } from './sex';
import { UserToRole } from './userToRole';
import { UserDevice } from './userDevice';
import { Contract } from './contract';
import { UserPaymentTerms } from './userPaymentTerms';


export interface User { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    username?: string | null;
    password?: string | null;
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    fullName?: string | null;
    type?: string | null;
    phoneNumber?: string | null;
    birthDate?: string | null;
    sex?: Sex;
    googleToken?: string | null;
    experience?: number;
    dailyRate?: number;
    isExternal?: boolean | null;
    resetToken?: string | null;
    userIdentifier?: string | null;
    teamTailorUserRef?: number | null;
    supplierId?: number | null;
    fiscalCode?: string | null;
    contracts?: Array<Contract> | null;
    contract?: Contract;
    contractId?: number | null;
    organization?: Organization;
    organizationId?: number | null;
    paymentTerms?: UserPaymentTerms;
    defaultAddress?: Address;
    roles?: Array<UserToRole> | null;
    userDevices?: Array<UserDevice> | null;
    cvs?: Array<Cv> | null;
}
export namespace User {
}


