/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VaultSecret } from './vaultSecret';
import { User } from './user';


export interface VaultSecretFolder { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    name?: string | null;
    description?: string | null;
    ownerUserId?: number;
    ownerUser?: User;
    secrets?: Array<VaultSecret> | null;
    folder?: VaultSecretFolder;
    folderId?: number | null;
}

