/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkingDayDataModel { 
    id?: number;
    uuid?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    deletedAt?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    deletedBy?: string | null;
    day?: string;
    description?: string | null;
    hours?: number | null;
    extra?: number | null;
    isHoliday?: boolean;
    timesheetId?: number;
}

