/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeSheet } from './timeSheet';


export interface WorkingDay { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    day?: string;
    description?: string | null;
    hours?: number;
    extra?: number;
    isHoliday?: boolean;
    timeSheet?: TimeSheet;
    timeSheetId?: number;
}

