/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentBuilderConfig } from './documentBuilderConfig';
import { Order } from './order';
import { FattureInCloudDocument } from './fattureInCloudDocument';


export interface Company { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    businessName?: string | null;
    vatNumber?: string | null;
    fiscalCode?: string | null;
    sdi?: string | null;
    referent?: string | null;
    email?: string | null;
    phone?: string | null;
    vatTypeId?: number | null;
    fattureInCloudCustomerId?: number | null;
    orders?: Array<Order> | null;
    documents?: Array<FattureInCloudDocument> | null;
    documentBuilderConfig?: DocumentBuilderConfig;
}

