/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Condition { 
    property: string | null;
    operator: string | null;
    evaluate?: string | null;
    value?: any | null;
    compareToProps?: Array<string> | null;
}

