/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateOrUpdateCompanyDataModel { 
    businessName?: string | null;
    vatNumber?: string | null;
    fiscalCode?: string | null;
    sdi?: string | null;
    referent?: string | null;
    email?: string | null;
    phone?: string | null;
    vatTypeId?: number | null;
    fattureInCloudCustomerId?: number | null;
}

