/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Currency { 
    id?: string | null;
    symbol?: string | null;
    exchangeRate?: string | null;
    htmlSymbol?: string | null;
}

