/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IssuedDocumentPaymentsListItem } from './issuedDocumentPaymentsListItem';
import { Entity } from './entity';
import { IssuedDocumentType } from './issuedDocumentType';
import { Language } from './language';
import { EiStatusEnum } from './eiStatusEnum';
import { IssuedDocumentItemsListItem } from './issuedDocumentItemsListItem';
import { Currency } from './currency';
import { IssuedDocumentExtraData } from './issuedDocumentExtraData';
import { ShowTotalsMode } from './showTotalsMode';
import { DocumentTemplate } from './documentTemplate';
import { PaymentMethod } from './paymentMethod';
import { IssuedDocumentEiData } from './issuedDocumentEiData';


export interface CustomIssueDocument { 
    type?: IssuedDocumentType;
    showTotals?: ShowTotalsMode;
    eiStatus?: EiStatusEnum;
    id?: number | null;
    entity?: Entity;
    number?: number | null;
    numeration?: string | null;
    date?: string | null;
    year?: number | null;
    currency?: Currency;
    language?: Language;
    subject?: string | null;
    visibleSubject?: string | null;
    rcCenter?: string | null;
    notes?: string | null;
    rivalsa?: number | null;
    cassa?: number | null;
    readonly amountCassa?: number | null;
    cassaTaxable?: number | null;
    amountCassaTaxable?: number | null;
    cassa2?: number | null;
    readonly amountCassa2?: number | null;
    cassa2Taxable?: number | null;
    amountCassa2Taxable?: number | null;
    globalCassaTaxable?: number | null;
    amountGlobalCassaTaxable?: number | null;
    withholdingTax?: number | null;
    withholdingTaxTaxable?: number | null;
    otherWithholdingTax?: number | null;
    stampDuty?: number | null;
    paymentMethod?: PaymentMethod;
    useSplitPayment?: boolean | null;
    useGrossPrices?: boolean | null;
    eInvoice?: boolean | null;
    eiData?: IssuedDocumentEiData;
    eiCassaType?: string | null;
    eiCassa2Type?: string | null;
    eiWithholdingTaxCausal?: string | null;
    eiOtherWithholdingTaxType?: string | null;
    eiOtherWithholdingTaxCausal?: string | null;
    itemsList?: Array<IssuedDocumentItemsListItem> | null;
    paymentsList?: Array<IssuedDocumentPaymentsListItem> | null;
    template?: DocumentTemplate;
    deliveryNoteTemplate?: DocumentTemplate;
    accInvTemplate?: DocumentTemplate;
    hMargins?: number | null;
    vMargins?: number | null;
    showPayments?: boolean | null;
    showPaymentMethod?: boolean | null;
    showNotificationButton?: boolean | null;
    showTspayButton?: boolean | null;
    deliveryNote?: boolean | null;
    accompanyingInvoice?: boolean | null;
    dnNumber?: number | null;
    dnDate?: string | null;
    dnAiPackagesNumber?: string | null;
    dnAiWeight?: string | null;
    dnAiCausal?: string | null;
    dnAiDestination?: string | null;
    dnAiTransporter?: string | null;
    dnAiNotes?: string | null;
    isMarked?: boolean | null;
    readonly amountNet?: number | null;
    readonly amountVat?: number | null;
    readonly amountGross?: number | null;
    amountDueDiscount?: number | null;
    readonly amountRivalsa?: number | null;
    amountRivalsaTaxable?: number | null;
    readonly amountWithholdingTax?: number | null;
    amountWithholdingTaxTaxable?: number | null;
    readonly amountOtherWithholdingTax?: number | null;
    amountOtherWithholdingTaxTaxable?: number | null;
    amountEnasarcoTaxable?: number | null;
    extraData?: IssuedDocumentExtraData;
    seenDate?: string | null;
    nextDueDate?: string | null;
    url?: string | null;
    dnUrl?: string | null;
    aiUrl?: string | null;
    readonly attachmentUrl?: string | null;
    attachmentToken?: string | null;
    eiRaw?: any | null;
    priceListId?: string | null;
    locked?: boolean | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    timesheetId?: number;
}
export namespace CustomIssueDocument {
}


