/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CvBasicInfo { 
    name?: string | null;
    title?: string | null;
    seniorityLabel?: string | null;
    fullOverview?: string | null;
    yearsExperience?: number | null;
    birthYear?: number | null;
    confirmed?: boolean;
    confirmedBy?: string | null;
    additionalNotes?: string | null;
    language?: string | null;
}

