/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CvChangeAddRequest { 
    deleted?: boolean | null;
    viewOrder?: number | null;
    oldValue?: string | null;
    newValue?: string | null;
    identifier?: string | null;
    section?: string | null;
}

