/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cv } from './cv';
import { User } from './user';


export interface CvChange { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    cvId?: number;
    cv?: Cv;
    user?: User;
    userId?: number;
    viewOrder?: number | null;
    deleted?: boolean | null;
    identifiedByAi?: boolean | null;
    oldValue?: string | null;
    newValue?: string | null;
    identifier?: string | null;
    section?: string | null;
    profileImageUrl?: string | null;
}

