/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CvExperience { 
    id?: string | null;
    period?: string | null;
    company?: string | null;
    role?: string | null;
    technologies?: string | null;
    description?: string | null;
    confirmed?: boolean;
    confirmedByAi?: boolean;
    confirmedBy?: string | null;
    additionalNotes?: string | null;
}

