/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { CvExtractedData } from './cvExtractedData';
import { CvChange } from './cvChange';
import { AiCvChangeSuggestion } from './aiCvChangeSuggestion';
import { ProcessingStatus } from './processingStatus';


export interface CvModelData { 
    id?: number;
    uuid?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    deletedAt?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    deletedBy?: string | null;
    userId?: number | null;
    user?: User;
    externalDataCandidateRefId?: string | null;
    externalDataCandidateName?: string | null;
    externalDataCandidateEmail?: string | null;
    externalDataCandidatePhone?: string | null;
    externalDataCandidatePersonalUrl?: string | null;
    externalDataCandidateImageUrl?: string | null;
    cvOcrData?: string | null;
    verified?: boolean | null;
    verifiedBy?: string | null;
    cvExtractedData?: CvExtractedData;
    aiResultString?: string | null;
    cvUrl?: string | null;
    elapsedTimeMs?: number;
    version?: number;
    status?: ProcessingStatus;
    confirmed?: boolean | null;
    changes?: Array<CvChange> | null;
    aiCvChangeSuggestions?: Array<AiCvChangeSuggestion> | null;
    cvApiLinkUrl?: string | null;
}
export namespace CvModelData {
}


