/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DropboxFileMedia { 
    id: number;
    name: string;
    key: string;
    uuid: string;
    url: string;
    size: number;
    folderPathSegments: Array<string>;
    folder: string;
    modifiedAt: string;
}

