/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const EiStatusEnum = {
    Attempt: 'Attempt',
    Missing: 'Missing',
    NotSent: 'NotSent',
    Sent: 'Sent',
    Pending: 'Pending',
    Processing: 'Processing',
    Error: 'Error',
    Discarded: 'Discarded',
    NotDelivered: 'NotDelivered',
    Accepted: 'Accepted',
    Rejected: 'Rejected',
    NoResponse: 'NoResponse',
    ManualAccepted: 'ManualAccepted',
    ManualRejected: 'ManualRejected'
} as const;
export type EiStatusEnum = typeof EiStatusEnum[keyof typeof EiStatusEnum];

