/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Email { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    to?: string | null;
    subject?: string | null;
    body?: string | null;
    from?: string | null;
    cc?: string | null;
    bcc?: string | null;
    attachments?: string | null;
    fromEmail?: string | null;
    sent?: boolean;
    errorMessage?: string | null;
    referenceId?: number;
    keyRef?: string | null;
}

