/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const EntityType = {
    Company: 'Company',
    Person: 'Person',
    Pa: 'Pa',
    Condo: 'Condo'
} as const;
export type EntityType = typeof EntityType[keyof typeof EntityType];

