/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityType } from './entityType';
import { PaymentMethod } from './paymentMethod';
import { VatType } from './vatType';
import { PaymentTermsType } from './paymentTermsType';


export interface Entity { 
    type?: EntityType;
    defaultPaymentTermsType?: PaymentTermsType;
    id?: number | null;
    code?: string | null;
    name?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    contactPerson?: string | null;
    vatNumber?: string | null;
    taxCode?: string | null;
    addressStreet?: string | null;
    addressPostalCode?: string | null;
    addressCity?: string | null;
    addressProvince?: string | null;
    addressExtra?: string | null;
    country?: string | null;
    countryIso?: string | null;
    email?: string | null;
    certifiedEmail?: string | null;
    phone?: string | null;
    fax?: string | null;
    notes?: string | null;
    defaultPaymentTerms?: number | null;
    defaultVat?: VatType;
    defaultPaymentMethod?: PaymentMethod;
    bankName?: string | null;
    bankIban?: string | null;
    bankSwiftCode?: string | null;
    shippingAddress?: string | null;
    eInvoice?: boolean | null;
    eiCode?: string | null;
    hasIntentDeclaration?: boolean | null;
    intentDeclarationProtocolNumber?: string | null;
    intentDeclarationProtocolDate?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
}
export namespace Entity {
}


