/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpiringUserDataModel { 
    userId?: number;
    fullName?: string | null;
    email?: string | null;
    orderEndDate?: string;
    daysToExpiration?: number;
    nextContractStartDate?: string | null;
    daysAfterExpirationToNextContract?: number | null;
}

