/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';


export interface FattureInCloudDocument { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    documentId?: number;
    month?: number;
    year?: number;
    company?: Company;
    companyId?: number;
}

