/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FilterDtoType = {
    Condition: 'Condition',
    Group: 'Group'
} as const;
export type FilterDtoType = typeof FilterDtoType[keyof typeof FilterDtoType];

