/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FreeUserDataModel { 
    userId?: number;
    fullName?: string | null;
    email?: string | null;
    lastActivityDate?: string | null;
    daysSinceLastActivity?: number | null;
}

