/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TalentExternalData } from './talentExternalData';
import { CvWithLink } from './cvWithLink';
import { Talent } from './talent';


export interface GetCvResponse { 
    cvs?: Array<CvWithLink> | null;
    talent?: Talent;
    externalData?: TalentExternalData;
}

