/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { VaultGroup } from './vaultGroup';


export interface GroupMember { 
    groupId?: number;
    group?: VaultGroup;
    userId?: number;
    user?: User;
}

