/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoicesDataModel } from './invoicesDataModel';


export interface InvoicesDataModelPaginatedResponse { 
    items?: Array<InvoicesDataModel> | null;
    totalCount?: number;
    pageSize?: number;
    pageIndex?: number;
}

