/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OriginalDocumentType } from './originalDocumentType';
import { VatKind } from './vatKind';


export interface IssuedDocumentEiData { 
    vatKind?: VatKind;
    originalDocumentType?: OriginalDocumentType;
    odNumber?: string | null;
    odDate?: string | null;
    cig?: string | null;
    cup?: string | null;
    paymentMethod?: string | null;
    bankName?: string | null;
    bankIban?: string | null;
    bankBeneficiary?: string | null;
    invoiceNumber?: string | null;
    invoiceDate?: string | null;
}
export namespace IssuedDocumentEiData {
}


