/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const IssuedDocumentStatus = {
    NotPaid: 'NotPaid',
    Paid: 'Paid',
    Reversed: 'Reversed'
} as const;
export type IssuedDocumentStatus = typeof IssuedDocumentStatus[keyof typeof IssuedDocumentStatus];

