/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IssuedDocumentExtraData { 
    multifattureSent?: number | null;
    tsCommunication?: boolean | null;
    tsFlagTipoSpesa?: number | null;
    tsPagamentoTracciato?: boolean | null;
    tsTipoSpesa?: string | null;
    tsOpposizione?: boolean | null;
    tsStatus?: number | null;
    tsFileId?: string | null;
    tsSentDate?: string | null;
    tsFullAmount?: boolean | null;
    importedBy?: string | null;
}

