/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VatType } from './vatType';


export interface IssuedDocumentItemsListItem { 
    id?: number | null;
    productId?: number | null;
    code?: string | null;
    name?: string | null;
    category?: string | null;
    description?: string | null;
    qty?: number | null;
    measure?: string | null;
    netPrice?: number | null;
    grossPrice?: number | null;
    vat?: VatType;
    notTaxable?: boolean | null;
    applyWithholdingTaxes?: boolean | null;
    discount?: number | null;
    discountHighlight?: boolean | null;
    inDn?: boolean | null;
    stock?: boolean | null;
    eiRaw?: any | null;
}

