/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const IssuedDocumentType = {
    Invoice: 'Invoice',
    Quote: 'Quote',
    Proforma: 'Proforma',
    Receipt: 'Receipt',
    DeliveryNote: 'DeliveryNote',
    CreditNote: 'CreditNote',
    Order: 'Order',
    WorkReport: 'WorkReport',
    SupplierOrder: 'SupplierOrder',
    SelfOwnInvoice: 'SelfOwnInvoice',
    SelfSupplierInvoice: 'SelfSupplierInvoice'
} as const;
export type IssuedDocumentType = typeof IssuedDocumentType[keyof typeof IssuedDocumentType];

