/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LanguageItem { 
    id?: string | null;
    language?: string | null;
    level?: string | null;
    confirmed?: boolean;
    confirmedBy?: string | null;
    additionalNotes?: string | null;
}

