/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const LogicalOperator = {
    And: 'And',
    Or: 'Or',
    Not: 'Not'
} as const;
export type LogicalOperator = typeof LogicalOperator[keyof typeof LogicalOperator];

