/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const OrderType = {
    Consulting: 'CONSULTING',
    Commissioning: 'COMMISSIONING'
} as const;
export type OrderType = typeof OrderType[keyof typeof OrderType];

