/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDataModel } from './userDataModel';
import { CompanyDataModel } from './companyDataModel';


export interface OrderDataModel { 
    id?: number;
    uuid?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    deletedAt?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    deletedBy?: string | null;
    worker?: UserDataModel;
    teamTailorUserRef?: number | null;
    company?: CompanyDataModel;
    internalRef?: string | null;
    externalRef?: string | null;
    projectName?: string | null;
    invoiceRowInfo?: string | null;
    startDate?: string | null;
    endDate?: string | null;
    hourRate?: number;
    resourceCosts?: number;
    hours?: number | null;
}

