/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const OriginalDocumentType = {
    Ordine: 'Ordine',
    Contratto: 'Contratto',
    Convenzione: 'Convenzione'
} as const;
export type OriginalDocumentType = typeof OriginalDocumentType[keyof typeof OriginalDocumentType];

