/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentMethodType } from './paymentMethodType';
import { PaymentAccount } from './paymentAccount';
import { PaymentMethodDetails } from './paymentMethodDetails';


export interface PaymentMethod { 
    type?: PaymentMethodType;
    id?: number | null;
    name?: string | null;
    isDefault?: boolean | null;
    defaultPaymentAccount?: PaymentAccount;
    details?: Array<PaymentMethodDetails> | null;
    bankIban?: string | null;
    bankName?: string | null;
    bankBeneficiary?: string | null;
    eiPaymentMethod?: string | null;
}
export namespace PaymentMethod {
}


