/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PaymentAccountType = {
    Standard: 'Standard',
    Bank: 'Bank'
} as const;
export type PaymentAccountType = typeof PaymentAccountType[keyof typeof PaymentAccountType];

