/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PublicDeviceDto { 
    deviceId?: number;
    userId?: number;
    deviceName?: string | null;
    publicKeySpkiBase64?: string | null;
    recoveryBackupBase64?: string | null;
}

