/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ReceivedDocumentType = {
    Expense: 'Expense',
    PassiveCreditNote: 'PassiveCreditNote',
    PassiveDeliveryNote: 'PassiveDeliveryNote',
    SelfInvoice: 'SelfInvoice'
} as const;
export type ReceivedDocumentType = typeof ReceivedDocumentType[keyof typeof ReceivedDocumentType];

