/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VatType } from './vatType';


export interface ReceivedDocumentItemsListItem { 
    id?: number | null;
    productId?: number | null;
    code?: string | null;
    name?: string | null;
    measure?: string | null;
    netPrice?: number | null;
    category?: string | null;
    qty?: number | null;
    vat?: VatType;
    stock?: number | null;
}

