/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentAccount } from './paymentAccount';
import { ReceivedDocumentPaymentsListItemPaymentTerms } from './receivedDocumentPaymentsListItemPaymentTerms';


export interface ReceivedDocumentPaymentsListItem { 
    id?: number | null;
    amount?: number | null;
    dueDate?: string | null;
    paidDate?: string | null;
    paymentTerms?: ReceivedDocumentPaymentsListItemPaymentTerms;
    status?: string | null;
    paymentAccount?: PaymentAccount;
}

