/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentTermsType } from './paymentTermsType';


export interface ReceivedDocumentPaymentsListItemPaymentTerms { 
    type?: PaymentTermsType;
    days?: number | null;
}
export namespace ReceivedDocumentPaymentsListItemPaymentTerms {
}


