/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Entity } from './entity';
import { ReceivedDocumentItemsListItem } from './receivedDocumentItemsListItem';
import { ReceivedDocumentType } from './receivedDocumentType';
import { Currency } from './currency';
import { ReceivedDocumentPaymentsListItem } from './receivedDocumentPaymentsListItem';


export interface ReceivedDocument { 
    type?: ReceivedDocumentType;
    id?: number | null;
    entity?: Entity;
    date?: string | null;
    category?: string | null;
    description?: string | null;
    amountNet?: number | null;
    amountVat?: number | null;
    amountWithholdingTax?: number | null;
    amountOtherWithholdingTax?: number | null;
    readonly amountGross?: number | null;
    amortization?: number | null;
    rcCenter?: string | null;
    invoiceNumber?: string | null;
    isMarked?: boolean | null;
    isDetailed?: boolean | null;
    eInvoice?: boolean | null;
    readonly nextDueDate?: string | null;
    currency?: Currency;
    taxDeductibility?: number | null;
    vatDeductibility?: number | null;
    itemsList?: Array<ReceivedDocumentItemsListItem> | null;
    paymentsList?: Array<ReceivedDocumentPaymentsListItem> | null;
    readonly attachmentUrl?: string | null;
    readonly attachmentPreviewUrl?: string | null;
    autoCalculate?: boolean | null;
    attachmentToken?: string | null;
    locked?: boolean | null;
    createdAt?: string | null;
    updatedAt?: string | null;
}
export namespace ReceivedDocument {
}


