/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const RecoveryMethodType = {
    RecoveryCode: 'RecoveryCode',
    AdminEscrow: 'AdminEscrow',
    ServerEscrow: 'ServerEscrow'
} as const;
export type RecoveryMethodType = typeof RecoveryMethodType[keyof typeof RecoveryMethodType];

