/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SecretPermission = {
    Read: 'Read',
    ReadWrite: 'ReadWrite',
    Owner: 'Owner'
} as const;
export type SecretPermission = typeof SecretPermission[keyof typeof SecretPermission];

