/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecoveryEnvelopeDto } from './recoveryEnvelopeDto';
import { SecretDeviceEnvelopeDto } from './secretDeviceEnvelopeDto';


export interface SecretResponse { 
    secretId?: number;
    ownerUserId?: number;
    title?: string | null;
    username?: string | null;
    ciphertextBase64?: string | null;
    nonceBase64?: string | null;
    tagBase64?: string | null;
    aad?: string | null;
    deviceEnvelopes?: Array<SecretDeviceEnvelopeDto> | null;
    recoveryEnvelopes?: Array<RecoveryEnvelopeDto> | null;
    note?: string | null;
    folderId?: number | null;
}

