/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ShowTotalsMode = {
    None: 'None',
    Nets: 'Nets',
    All: 'All'
} as const;
export type ShowTotalsMode = typeof ShowTotalsMode[keyof typeof ShowTotalsMode];

