/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TalentExternalData { 
    id?: string | null;
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    internal?: boolean;
    resumeSummary?: string | null;
    resume?: string | null;
    originalResume?: string | null;
    profileUrl?: string | null;
    tags?: Array<string> | null;
    createdAt?: string | null;
    updatedAt?: string | null;
}

