/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Talent { 
    id?: number | null;
    identifier?: string | null;
    teamTailorId?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    sex?: any | null;
    type?: string | null;
    frameworkAgreementOrContract?: any | null;
    signingDate?: any | null;
    companyEmail?: string | null;
    personalEmail?: string | null;
    phone?: string | null;
    location?: string | null;
    language?: any | null;
    availability?: string | null;
    lastSync?: string | null;
    workStartYear?: any | null;
    seniority?: any | null;
    role?: any | null;
    rateDay?: number | null;
    cv?: any | null;
    notes?: any | null;
    status?: string | null;
    welcomeKit?: any | null;
    picture?: string | null;
    createdAt?: any | null;
    updatedAt?: any | null;
    reports?: Array<object> | null;
    fullName?: string | null;
    lastReport?: object;
}

