/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TestEmailRequest { 
    to: string | null;
    subject: string | null;
    key: string | null;
    templateData?: { [key: string]: any; } | null;
}

