/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDataModel } from './userDataModel';
import { CompanyDataModel } from './companyDataModel';
import { OrderDataModel } from './orderDataModel';
import { TimeSheetAccountingInfo } from './timeSheetAccountingInfo';
import { WorkingDayDataModel } from './workingDayDataModel';
import { MediaDataModel } from './mediaDataModel';


export interface TimeSheetDataModel { 
    id?: number;
    uuid?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    deletedAt?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    deletedBy?: string | null;
    user?: UserDataModel;
    details?: number;
    client?: CompanyDataModel;
    month?: number;
    year?: number;
    submitted?: boolean;
    submittedDate?: string | null;
    approved?: boolean;
    approvedDate?: string | null;
    total?: number;
    workingDays: Array<WorkingDayDataModel>;
    order?: OrderDataModel;
    documentId?: number | null;
    accountingInfo?: TimeSheetAccountingInfo;
    medias?: Array<MediaDataModel> | null;
    paidDocumentId?: number | null;
}

