/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeSheet } from './timeSheet';
import { Media } from './media';


export interface TimesheetMedia { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    timeSheetId: number;
    timeSheet?: TimeSheet;
    mediaId: number;
    media?: Media;
    isProforma?: boolean;
}

