/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeSheet } from './timeSheet';


export interface TimeSheetAccountingInfo { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    timeSheet?: TimeSheet;
    timeSheetId?: number;
    consultantPaymentDate?: string;
    clientPaymentDate?: string;
    paid?: boolean;
}

