/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { User } from './user';
import { TimesheetMedia } from './timesheetMedia';
import { TimeSheetAccountingInfo } from './timeSheetAccountingInfo';
import { WorkingDay } from './workingDay';


export interface TimeSheet { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    submitted?: boolean;
    submittedDate?: string | null;
    approved?: boolean | null;
    approvedDate?: string | null;
    month?: number;
    year?: number;
    totHours?: number | null;
    totInvoice?: number | null;
    approvedBy?: User;
    approvedById?: number | null;
    user?: User;
    userId?: number | null;
    order?: Order;
    orderId?: number | null;
    days?: Array<WorkingDay> | null;
    documentId?: number | null;
    paidDocumentId?: number | null;
    accountingInfo?: TimeSheetAccountingInfo;
    medias?: Array<TimesheetMedia> | null;
    readonly hideForExpiration?: boolean;
}

