/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TrainingType = {
    Training: 'Training',
    Certificate: 'Certificate'
} as const;
export type TrainingType = typeof TrainingType[keyof typeof TrainingType];

