/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UiFieldMetadata } from './uiFieldMetadata';


export interface UiResourceRefMetadata { 
    name: string | null;
    title?: string | null;
    api?: string | null;
    postApi?: string | null;
    patchApi?: string | null;
    deleteApi?: string | null;
    getByIdApi?: string | null;
    pageSize?: number;
    defaultSort?: string | null;
    enablePost?: boolean | null;
    enablePut?: boolean | null;
    enablePatch?: boolean | null;
    enableDelete?: boolean | null;
    allowedIncludesKeys?: Array<string> | null;
    allowedFilterableKeys?: Array<string> | null;
    fields?: { [key: string]: UiFieldMetadata; } | null;
}

