/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sex } from './sex';


export interface UpdateUserDataModel { 
    firstName: string | null;
    lastName: string | null;
    userIdentifier: string;
    phoneNumber: string;
    teamTailorUserRef?: number | null;
    username: string | null;
    email: string | null;
    password?: string | null;
    confirmPassword?: string | null;
    birthDate: string;
    sex: Sex;
    roles: Array<number> | null;
    paymentTerms?: number | null;
    supplierId?: number;
}
export namespace UpdateUserDataModel {
}


