/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDataModel } from './roleDataModel';
import { Sex } from './sex';
import { ModelSupplierDataModel } from './modelSupplierDataModel';


export interface UserDataModel { 
    id?: number;
    uuid?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    deletedAt?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    deletedBy?: string | null;
    fullName: string;
    userIdentifier: string;
    firstName: string;
    lastName: string;
    username: string;
    phoneNumber?: string | null;
    email: string;
    birthDate: string;
    sex: Sex;
    roles: Array<RoleDataModel>;
    paymentTerms?: number | null;
    supplierDataModel?: ModelSupplierDataModel;
    teamTailorUserRef?: number | null;
    readonly talentId?: number | null;
}
export namespace UserDataModel {
}


