/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const VatKind = {
    I: 'I',
    D: 'D',
    S: 'S'
} as const;
export type VatKind = typeof VatKind[keyof typeof VatKind];

