/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VatType { 
    id?: number | null;
    value?: number | null;
    description?: string | null;
    notes?: string | null;
    eInvoice?: boolean | null;
    eiType?: string | null;
    eiDescription?: string | null;
    readonly editable?: boolean | null;
    isDisabled?: boolean | null;
    _default?: boolean | null;
}

