/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecretDeviceEnvelope } from './secretDeviceEnvelope';
import { RecoveryEnvelope } from './recoveryEnvelope';
import { User } from './user';
import { VaultSecretFolder } from './vaultSecretFolder';


export interface VaultSecret { 
    id?: number;
    deletedAt?: string | null;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string | null;
    deletedBy?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
    ownerUserId?: number;
    ownerUser?: User;
    title?: string | null;
    username?: string | null;
    note?: string | null;
    ciphertextBase64?: string | null;
    nonceBase64?: string | null;
    tagBase64?: string | null;
    aad?: string | null;
    deviceEnvelopes?: Array<SecretDeviceEnvelope> | null;
    recoveryEnvelopes?: Array<RecoveryEnvelope> | null;
    folder?: VaultSecretFolder;
    folderId?: number | null;
}

