/**
 * WebApiPlanner
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicDeviceDto } from './publicDeviceDto';


export interface VaultUserDto { 
    userId?: number;
    userUuid?: string;
    email?: string | null;
    fullName?: string | null;
    deviceCount?: number;
    devices?: Array<PublicDeviceDto> | null;
}

