export * from './auth.service';
import { AuthService } from './auth.service';
export * from './clientConfig.service';
import { ClientConfigService } from './clientConfig.service';
export * from './company.service';
import { CompanyService } from './company.service';
export * from './cv.service';
import { CvService } from './cv.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './invoices.service';
import { InvoicesService } from './invoices.service';
export * from './mailTemplate.service';
import { MailTemplateService } from './mailTemplate.service';
export * from './medias.service';
import { MediasService } from './medias.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './role.service';
import { RoleService } from './role.service';
export * from './timesheet.service';
import { TimesheetService } from './timesheet.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './vault.service';
import { VaultService } from './vault.service';
export * from './webApiPlanner.service';
import { WebApiPlannerService } from './webApiPlanner.service';
export * from './workingDay.service';
import { WorkingDayService } from './workingDay.service';
export const APIS = [AuthService, ClientConfigService, CompanyService, CvService, DashboardService, InvoicesService, MailTemplateService, MediasService, OrderService, RoleService, TimesheetService, UserService, VaultService, WebApiPlannerService, WorkingDayService];
